version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        restart: always
        depends_on:
            - alertmanager

    blackbox-exporter:
        image: prom/blackbox-exporter
        hostname: monitoring
        ports:
          - 9115:9115
        command:
          - '--config.file=/etc/blackbox/config.yml'
        restart: always
        volumes:
          - ./blackbox:/etc/blackbox/

    alertmanager-bot:
        command:
        - --alertmanager.url=http://alertmanager:9093
        - --log.level=info
        - --store=bolt
        - --bolt.path=/data/bot.db
        environment:
          TELEGRAM_ADMIN: "***"
          TELEGRAM_TOKEN: ***
        image: metalmatze/alertmanager-bot:0.4.3
        ports:
        - 127.0.0.1:8080:8080
        restart: always
        volumes:
        - ./data:/data

    alertmanager:
      image: prom/alertmanager:v0.21.0
      ports:
        - 9093:9093
      volumes:
        - ./alertmanager/:/etc/alertmanager/
      restart: always
      command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/etc/alertmanager/data'
      user: "$UID:$GID"

    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 127.0.0.1:9100:9100
        restart: always

    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./grafana:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        restart: always
        user: "$UID:$GID"
